---
# tasks file for ansible-role-maven

- name: "{{ maven_version }} checksum"
  set_fact:
    maven_checksum: e7ebd0b8d6811b42a5dad91fb27fe9b4
  when: ("{{ maven_version }}" == "3.3.9")

- name: "{{ maven_version }} checksum"
  set_fact:
    maven_checksum: c062cb57ca81615cc16500af332b93bd
  when: ("{{ maven_version }}" == "3.5.0")

- block:

  - name: "Check if maven is alresy installed"
    shell: "{{ maven_link }} -v | grep {{ maven_version }}"
    args:
      executable: /bin/bash

  - debug:
      msg: "maven {{ maven_version }} is installed"

  rescue:

  - name: "Install unzip"
    package:
      name: unzip
      state: latest

  - name: "Download maven {{ maven_version }}"
    unarchive:
      src: "{{ maven_download_url }}"
      dest: "{{ maven_base_dir }}"
      remote_src: True

  - name: "Add maven symlink to path"
    file:
      src: "{{ maven_base_dir }}/{{ maven_extract_dir }}/bin/mvn"
      dest: "{{ maven_link }}"
      owner: root
      group: root
      state: link

  - name: "Validate maven version"
    shell: "{{ maven_link }} -v | grep {{ maven_version }}"
    args:
      executable: /bin/bash
    register: maven_ver

  - fail:
      msg: "Seems to be maven {{ maven_version }} is missing ... aborting"
    when: maven_ver.rc != 0
